import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";
import About from "@/components/sections/about";


export const metadata = {
  title: "Code Arcus",
  description: "Generated by create next app",
  icon: "/file.svg",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
         
        {children}
        <About/>
      </body>
    </html>
  );
}
